import React,{useEffect,useRef,useState} from 'react';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionStatus} from 'genlayer-js/types';
import CreateGrant from './CreateGrant.jsx';
import SubmitEvidence from './SubmitEvidence.jsx';
const CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||'';
const configured=/^0x[a-fA-F0-9]{40}$/.test(CONTRACT)&&CONTRACT.toLowerCase()!=='0xfb34bb3338097b22ed036194bb796263920c331a';
const client=()=>createClient({chain:studionet});
const short=(v='')=>v.length>15?`${v.slice(0,8)}…${v.slice(-6)}`:v;
const statuses={0:'PLANNED',1:'CLAIMED',2:'SUBMITTED',3:'APPROVED',4:'PAID',5:'REJECTED',6:'REFUNDED',7:'UNAVAILABLE',9:'EXPIRED'};
const gen=v=>{const n=BigInt(v||0);return `${n/10n**18n}.${(n%10n**18n).toString().padStart(18,'0').replace(/0+$/,'')||'0'}`};
const read=async(name,args=[])=>JSON.parse(await client().readContract({address:CONTRACT,functionName:name,args}));
export default function App(){
 const [account,setAccount]=useState(''),[grants,setGrants]=useState([]),[milestones,setMilestones]=useState([]),[accounting,setAccounting]=useState({});
 const [selected,setSelected]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[history,setHistory]=useState(null),[hash,setHash]=useState('');const lock=useRef(false);
 async function refresh(){if(!configured)return;const counts=await read('get_counts');const gs=await Promise.all(Array.from({length:counts.grant_count},(_,i)=>read('get_grant',[BigInt(i)])));const ms=await Promise.all(Array.from({length:counts.milestone_count},(_,i)=>read('get_milestone',[BigInt(i)])));setGrants(gs);setMilestones(ms);setAccounting(await read('get_accounting'))}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message));const eth=window.ethereum;const changed=a=>setAccount(a[0]||'');eth?.request({method:'eth_accounts'}).then(changed).catch(()=>{});eth?.on?.('accountsChanged',changed);return()=>eth?.removeListener?.('accountsChanged',changed)},[]);
 async function connect(){try{if(!window.ethereum)throw new Error('Install a compatible wallet.');setAccount((await window.ethereum.request({method:'eth_requestAccounts'}))[0]||'')}catch(e){setNotice(e.message)}}
 async function write(functionName,args,value){
  if(lock.current)return;lock.current=true;setBusy(true);setHistory(null);setHash('');
  try{
   if(!configured||!account)throw new Error('Deploy the revised contract and connect wallet first.');
   const chain=await window.ethereum.request({method:'eth_chainId'});if(BigInt(chain)!==61999n)throw new Error('Switch wallet to Studionet (61999).');
   const c=createClient({chain:studionet,provider:window.ethereum,account});setNotice(`Confirm ${functionName} in wallet.`);
   const tx=await c.writeContract({address:CONTRACT,functionName,args,...(value?{value}:{})});setHash(tx);setNotice('Submitted. Waiting for finality; do not send a duplicate.');
   localStorage.setItem(`grantgate:${CONTRACT}:${account}`,tx);
   await client().waitForTransactionReceipt({hash:tx,status:TransactionStatus.FINALIZED});await refresh();
   if(functionName==='create_grant')setNotice('Transaction finalized. Inspect the refreshed grant ledger and transaction return value to confirm creation.');
   else {const state=await read('get_milestone',[args[0]]);setNotice(`Transaction finalized. Current milestone: ${statuses[state.status]}, submission ${state.attempts}, verdict ${state.verdict}. Finality alone does not prove the requested action succeeded.`)}
   localStorage.removeItem(`grantgate:${CONTRACT}:${account}`);
  }catch(e){setNotice(`${e.message}. If a transaction hash exists, inspect it before retrying.`)}finally{lock.current=false;setBusy(false)}
 }
 useEffect(()=>{if(account&&configured){const pending=localStorage.getItem(`grantgate:${CONTRACT}:${account}`);if(pending){setHash(pending);setNotice('A previous transaction needs inspection before sending another. Open its explorer link and refresh state.')}}},[account]);
 async function showHistory(m){try{const records=[];for(let n=1;n<=m.attempts;n++){const submission=await read('get_submission',[BigInt(m.milestone_id),BigInt(n)]);const assessments=[];for(let a=1;a<=submission.assessment_count;a++)assessments.push(await read('get_assessment',[BigInt(m.milestone_id),BigInt(n),BigInt(a)]));records.push({submission,assessments})}setHistory(records)}catch(e){setNotice(e.message)}}
 const grant=grants.find(g=>g.grant_id===selected)||grants[0];const ms=milestones.filter(m=>m.grant_id===grant?.grant_id);
 const recipient=account&&account.toLowerCase()===grant?.recipient.toLowerCase(),sponsor=account&&account.toLowerCase()===grant?.sponsor.toLowerCase();
 return <div className="app"><header><a className="brand" href="#top"><img alt="GrantGate logo" src="/grant-gate-logo.png"/><div><b>GrantGate</b><span>Evidence-bound funding</span></div></a><nav><a href="#grants">Grants</a><a href="#protocol">Protocol</a></nav><div className="head-actions"><span className="network">Studionet · 61999</span><button className="wallet" onClick={connect}>{account?short(account):'Connect wallet'}</button></div></header>
 <main id="top"><section className="hero"><div className="eyebrow">NATIVE GEN CUSTODY · VALIDATOR CONSENSUS</div><h1>Fund outcomes.<br/><em>Release on evidence.</em></h1><p>Agree on milestones before work begins. Submit delivery later. Validators retrieve pinned artifacts and assess them against the sponsor’s immutable criteria.</p><a className="primary" href="#grants">Create a grant</a></section><aside className="vault"><div className="vault-top"><div><span>Active locked custody</span><strong>{gen(accounting.active_locked)} GEN</strong></div></div><div className="vault-grid"><div><span>Deposited</span><b>{gen(accounting.total_deposited)} GEN</b></div><div><span>Released</span><b>{gen(accounting.total_paid)} GEN</b></div><div><span>Refunded</span><b>{gen(accounting.total_refunded)} GEN</b></div><div><span>Contract</span><b>{configured?short(CONTRACT):'Awaiting new revision'}</b></div></div><p>Unavailable evidence never authorizes payout.</p></aside>
 <section className="stats"><div><span>Grants</span><strong>{grants.length}</strong></div><div><span>Milestones</span><strong>{milestones.length}</strong></div><div><span>Approved / paid</span><strong>{milestones.filter(m=>[3,4].includes(m.status)).length}</strong></div><button disabled={busy||!configured} onClick={()=>refresh().catch(e=>setNotice(e.message))}>Refresh on-chain</button></section>
 <section id="grants"><h2>Grant builder & live ledger</h2><div className="notice" role="status">{notice}{hash&&<p><a target="_blank" rel="noreferrer" href={`https://explorer-studio.genlayer.com/transactions/${hash}`}>Inspect transaction {short(hash)}</a></p>}</div><CreateGrant canSubmit={configured&&account&&!busy} onCreate={(args,value)=>write('create_grant',args,value)}/>
 {!configured?<div className="empty"><h3>Revised contract deployment required</h3><p>The old deployment is incompatible with this workflow. Connect the new address only after checking its source and ABI.</p></div>:!grant?<div className="empty">No grants yet.</div>:<><label>Select grant<select value={grant.grant_id} onChange={e=>{setSelected(Number(e.target.value));setHistory(null)}}>{grants.map(g=><option key={g.grant_id} value={g.grant_id}>#{g.grant_id} · {g.title}</option>)}</select></label><article className="grant-card"><h3>{grant.title}</h3><p className="break">Sponsor: {grant.sponsor}<br/>Recipient: {grant.recipient}<br/>Repository policy: {grant.repository}</p>{ms.map((m,i)=>{const now=Date.now()/1000;const deliveryOpen=now<=m.deadline_at;const cutoff=m.deadline_at+([2,7].includes(m.status)?86400:0);return <div className={`mile s${m.status}`} key={m.milestone_id}><div className="mile-index">{i+1}</div><div><h4>{m.criteria}</h4><p>Remaining: {gen(m.amount_wei)} GEN · deadline {new Date(m.deadline_at*1000).toLocaleString()}</p><p>Submission {m.attempts} · {m.verdict}</p><div className="mile-actions"><button disabled={busy||!recipient||!deliveryOpen||m.status!==0||(i>0&&ms[i-1].status!==4)} onClick={()=>write('claim_milestone',[BigInt(m.milestone_id)])}>Claim</button>{[2,7].includes(m.status)&&<button disabled={busy||!account||now>cutoff} onClick={()=>write('assess_milestone',[BigInt(m.milestone_id),BigInt(m.attempts)])}>Assess current submission</button>}{m.status===3&&<button disabled={busy||!(recipient||sponsor)} onClick={()=>write('pay_milestone',[BigInt(m.milestone_id)])}>Release tranche</button>}{![3,4,6,9].includes(m.status)&&<button disabled={busy||!account||now<=cutoff} onClick={()=>write('expire_milestone',[BigInt(m.milestone_id)])}>Expire</button>}{m.status===9&&<button disabled={busy||!sponsor} onClick={()=>write('refund_expired_milestone',[BigInt(m.milestone_id)])}>Refund sponsor</button>}<button onClick={()=>showHistory(m)}>Evidence history</button></div>{[1,5,7].includes(m.status)&&recipient&&<SubmitEvidence grant={grant} milestone={m} disabled={busy||!deliveryOpen} onSubmit={args=>write('submit_milestone',args)}/>}</div><span className="status">{statuses[m.status]}</span></div>})}</article></>}{history&&<pre className="history">{JSON.stringify(history,null,2)}</pre>}</section>
 <section id="protocol" className="protocol"><h2>Delivery, review, settlement</h2><div className="steps"><div><h3>1. Bind</h3><p>The sponsor fixes a repository, recipient, amounts and criteria. Recipient submissions bind chain, contract, grant, milestone and nonce to pinned Git commits.</p></div><div><h3>2. Verify</h3><p>Validators hash the manifest and actual UTF-8 artifacts, then assess criteria. New submissions keep prior evidence and assessments readable.</p></div><div><h3>3. Settle</h3><p>Approved tranches pay once. Pending or unavailable submissions get a 24-hour review grace after the delivery deadline. Only expired tranches refund the sponsor.</p></div></div></section>{configured&&<a target="_blank" rel="noreferrer" href={`https://explorer-studio.genlayer.com/address/${CONTRACT}`}>Open deployed contract</a>}</main><footer>GrantMilestoneEvidenceEscrow · GrantGate · Testnet software, not an independent security audit.</footer></div>
}
