import React,{useEffect,useState} from 'react';
import {ArrowUpRight,Check,Clock3,FileCheck2,LockKeyhole,RefreshCw,ShieldCheck,WalletCards} from 'lucide-react';
import {createClient} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionStatus} from 'genlayer-js/types';
import CreateGrant from './CreateGrant.jsx';

const CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||'';
const configured=/^0x[a-fA-F0-9]{40}$/.test(CONTRACT);
const client=()=>createClient({chain:studionet});
const short=(v='')=>v.length>14?`${v.slice(0,7)}…${v.slice(-5)}`:v;
const statuses={0:'PLANNED',1:'CLAIMED',2:'SUBMITTED',3:'APPROVED',4:'PAID',5:'REJECTED',6:'REFUNDED',7:'UNAVAILABLE',9:'EXPIRED'};
const formatGen=v=>(Number(v||0)/1e18).toLocaleString(undefined,{maximumFractionDigits:4});

export default function App(){
 const [account,setAccount]=useState(''); const [grants,setGrants]=useState([]); const [milestones,setMilestones]=useState([]); const [accounting,setAccounting]=useState({}); const [loading,setLoading]=useState(false); const [notice,setNotice]=useState('');
 async function connect(){if(!window.ethereum)return alert('Install a compatible wallet.');const [a]=await window.ethereum.request({method:'eth_requestAccounts'});setAccount(a)}
 async function refresh(){if(!configured)return;setLoading(true);try{const c=client();const raw=await c.readContract({address:CONTRACT,functionName:'get_counts',args:[]});const counts=JSON.parse(raw);const acc=JSON.parse(await c.readContract({address:CONTRACT,functionName:'get_accounting',args:[]}));const gs=await Promise.all(Array.from({length:counts.grant_count},(_,i)=>c.readContract({address:CONTRACT,functionName:'get_grant',args:[BigInt(i)]}).then(JSON.parse)));const ms=await Promise.all(Array.from({length:counts.milestone_count},(_,i)=>c.readContract({address:CONTRACT,functionName:'get_milestone',args:[BigInt(i)]}).then(JSON.parse)));setGrants(gs);setMilestones(ms);setAccounting(acc)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 async function write(functionName,args,value){try{if(!account)throw new Error('Connect wallet first.');const c=createClient({chain:studionet,provider:window.ethereum,account});setNotice(`Submitting ${functionName}…`);const hash=await c.writeContract({address:CONTRACT,functionName,args,...(value?{value}:{})});setNotice(`Waiting for finality: ${short(hash)}`);await client().waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED});await refresh();setNotice(`${functionName} finalized and state reconciled.`)}catch(e){setNotice(e.message||'Transaction failed')}}
 const demo=grants[0]; const demoMs=milestones.filter(m=>m.grant_id===demo?.grant_id);
 return <div className="app">
  <header><a className="brand" href="#top"><img src="/grant-gate-logo.png"/><div><b>GrantGate</b><span>Evidence-bound funding</span></div></a><nav><a href="#grants">Grants</a><a href="#protocol">Protocol</a><a href="#evidence">Evidence</a></nav><div className="head-actions"><span className="network"><i/>Studionet · 61999</span><button className="wallet" onClick={connect}><WalletCards size={16}/>{account?short(account):'Connect wallet'}</button></div></header>
  <main id="top">
   <section className="hero"><div className="eyebrow"><ShieldCheck size={15}/> Native GEN custody · validator consensus</div><h1>Fund outcomes.<br/><em>Release on evidence.</em></h1><p>Turn a grant into sequenced, auditable milestones. Sponsors commit the source policy up front; GenLayer validators assess canonical deliverables before each tranche moves.</p><div className="hero-actions"><a className="primary" href="#grants">Open grant ledger <ArrowUpRight size={17}/></a><a className="secondary" href="#protocol">See verification model</a></div><div className="proof-row"><span><Check/>Sponsor-fixed source</span><span><Check/>Sequential tranches</span><span><Check/>Retry-safe uncertainty</span></div></section>
   <aside className="vault"><div className="vault-top"><div><span>Protocol custody</span><strong>{formatGen(accounting.active_locked)} GEN</strong></div><LockKeyhole/></div><div className="vault-grid"><div><span>Deposited</span><b>{formatGen(accounting.total_deposited)} GEN</b></div><div><span>Released</span><b>{formatGen(accounting.total_paid)} GEN</b></div><div><span>Refunded</span><b>{formatGen(accounting.total_refunded)} GEN</b></div><div><span>Contract</span><b>{configured?short(CONTRACT):'Awaiting deploy'}</b></div></div><div className="vault-note"><FileCheck2/><span>Funds move only after deterministic bindings and bounded semantic consensus both pass.</span></div></aside>
   <section className="stats"><div><span>Active grants</span><strong>{grants.length}</strong></div><div><span>Milestones</span><strong>{milestones.length}</strong></div><div><span>Approved / paid</span><strong>{milestones.filter(m=>[3,4].includes(m.status)).length}</strong></div><button onClick={refresh}><RefreshCw className={loading?'spin':''}/>Refresh on-chain</button></section>
   <section id="grants" className="ledger"><div className="section-title"><div><span>GRANT BUILDER & LIVE LEDGER</span><h2>Design the tranches</h2></div><p>Enter the grant now. Transaction submission unlocks after deployment and wallet connection.</p></div>{notice&&<div className="notice">{notice}</div>}<CreateGrant canSubmit={configured&&account} onCreate={(args,value)=>write('create_grant',args,value)}/>
    {!configured?<div className="empty"><LockKeyhole/><h3>Contract ready for deployment</h3><p>Add the new Studionet address to <code>VITE_CONTRACT_ADDRESS</code> after source-parity verification.</p></div>:!demo?<div className="empty"><Clock3/><h3>No grants registered yet</h3><p>Create the first funded grant in GenLayer Studio, then operate it here.</p></div>:<article className="grant-card"><div className="grant-head"><div><span>GRANT #{demo.grant_id}</span><h3>{demo.title}</h3></div><span className="funded">{formatGen(demo.remaining_wei)} GEN remaining</span></div><div className="parties"><div><span>Sponsor</span><b>{short(demo.sponsor)}</b></div><div><span>Recipient</span><b>{short(demo.recipient)}</b></div><div><span>Evidence revision</span><b>{short(demo.revision)}</b></div></div><div className="timeline">{demoMs.map((m,i)=><div className={`mile s${m.status}`} key={m.milestone_id}><div className="mile-index">{m.status===4?<Check/>:i+1}</div><div><span>MILESTONE {i+1}</span><h4>{m.criteria}</h4><p>{formatGen(m.amount_wei)} GEN · manifest {short(m.manifest_sha256)}</p><div className="mile-actions">{m.status===0&&<button onClick={()=>write('claim_milestone',[BigInt(m.milestone_id)])}>Claim</button>}{[1,5,7].includes(m.status)&&<button onClick={()=>write('submit_milestone',[BigInt(m.milestone_id)])}>Submit</button>}{[2,7].includes(m.status)&&<button onClick={()=>write('assess_milestone',[BigInt(m.milestone_id)])}>Assess</button>}{m.status===3&&<button onClick={()=>write('pay_milestone',[BigInt(m.milestone_id)])}>Release tranche</button>}{![3,4,6,9].includes(m.status)&&<button onClick={()=>write('expire_milestone',[BigInt(m.milestone_id)])}>Check expiry</button>}{m.status===9&&<button onClick={()=>write('refund_expired_milestone',[BigInt(m.milestone_id)])}>Refund sponsor</button>}</div></div><div className="status">{statuses[m.status]}</div></div>)}</div></article>}
   </section>
   <section id="protocol" className="protocol"><div className="section-title"><div><span>CONSEQUENCE BOUNDARY</span><h2>Two layers must agree</h2></div></div><div className="steps"><div><b>01</b><FileCheck2/><h3>Bind</h3><p>Manifest bytes must match the sponsor-committed SHA-256 and exact grant, milestone, recipient and revision.</p></div><div><b>02</b><ShieldCheck/><h3>Judge</h3><p>Validators independently assess whether concrete deliverables satisfy the bounded milestone criteria.</p></div><div><b>03</b><LockKeyhole/><h3>Enforce</h3><p>Deterministic lifecycle, deadline, sequencing and accounting gates authorize a one-shot transfer.</p></div></div></section>
   <section id="evidence" className="evidence"><div><span>PUBLIC VERIFICATION</span><h2>Every decision stays inspectable.</h2><p>Canonical manifest URL, content commitment, verdict diagnostics, tranche accounting and terminal state remain readable on-chain.</p></div><a href={configured?`https://explorer-studio.genlayer.com/address/${CONTRACT}`:'#'} target="_blank">Open contract explorer <ArrowUpRight/></a></section>
  </main><footer><div className="brand"><img src="/grant-gate-logo.png"/><div><b>GrantGate</b><span>Built for GenLayer</span></div></div><p>Evidence-bound funding without a centralized grant administrator.</p></footer>
 </div>
}
