import React,{useState} from 'react';
import {buildPlan} from './forms.js';
export default function CreateGrant({onCreate,canSubmit}){
 const [title,setTitle]=useState(''),[recipient,setRecipient]=useState(''),[repository,setRepository]=useState('');
 const [rows,setRows]=useState([{gen:'0.001',seconds:'86400',criteria:''}]),[error,setError]=useState('');
 const change=(i,key,value)=>setRows(rows.map((r,n)=>n===i?{...r,[key]:value}:r));
 async function submit(e){e.preventDefault();setError('');try{const {plan,value}=buildPlan(rows);await onCreate([title,recipient,repository,JSON.stringify(plan)],value)}catch(e){setError(e.message)}}
 return <form className="create-form" onSubmit={submit}><h3>Create a funded grant</h3><p>Fix the recipient, repository and acceptance criteria now. Submit evidence after delivery. Deadlines run from grant creation.</p><div className="form-grid"><label>Title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Recipient wallet<input required pattern="0x[a-fA-F0-9]{40}" value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>GitHub repository<input required placeholder="owner/repository" pattern="[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+" value={repository} onChange={e=>setRepository(e.target.value)}/></label></div>{rows.map((r,i)=><fieldset key={i}><legend>Milestone {i+1}</legend><div className="form-grid"><label>Amount (GEN)<input required inputMode="decimal" value={r.gen} onChange={e=>change(i,'gen',e.target.value)}/></label><label>Deadline offset (seconds)<input required type="number" min="300" max="31536000" value={r.seconds} onChange={e=>change(i,'seconds',e.target.value)}/></label></div><label>Acceptance criteria<textarea required maxLength={1200} value={r.criteria} onChange={e=>change(i,'criteria',e.target.value)}/></label></fieldset>)}<button type="button" disabled={rows.length>=6} onClick={()=>setRows([...rows,{gen:'0.001',seconds:String(Number(rows.at(-1).seconds)+86400),criteria:''}])}>Add milestone</button>{rows.length>1&&<button type="button" onClick={()=>setRows(rows.slice(0,-1))}>Remove last</button>}{error&&<p role="alert">{error}</p>}<button className="primary" disabled={!canSubmit}>Lock exact tranche sum</button></form>
}
