import React,{useState} from 'react';
import {LockKeyhole} from 'lucide-react';

export default function CreateGrant({onCreate,disabled}){
 const [open,setOpen]=useState(false);
 const [form,setForm]=useState({title:'Public-interest tooling grant',recipient:'',base:'',revision:'',plan:'[{"amount_wei":"1000000000000000","deadline_seconds":86400,"criteria":"Publish a working prototype and a reproducible delivery report.","manifest_sha256":""}]'});
 async function submit(e){e.preventDefault();const plan=JSON.parse(form.plan);const value=plan.reduce((sum,item)=>sum+BigInt(item.amount_wei),0n);await onCreate([form.title,form.recipient,form.base,form.revision,JSON.stringify(plan)],value);setOpen(false)}
 return <div className="create-shell"><button className="create-toggle" disabled={disabled} onClick={()=>setOpen(!open)}>{open?'Close builder':'Create funded grant'}</button>{open&&<form className="create-form" onSubmit={submit}><h3>Commit the grant before work begins</h3><p>The exact GEN deposit must equal every milestone amount. Manifest locations and SHA-256 commitments become immutable.</p><div className="form-grid"><label>Grant title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Recipient wallet<input required placeholder="0x…" value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})}/></label><label>Immutable manifest base<input required placeholder="https://raw.githubusercontent.com/org/repo/<40-sha>/grant-0" value={form.base} onChange={e=>setForm({...form,base:e.target.value})}/></label><label>40-character revision<input required pattern="[a-fA-F0-9]{40}" value={form.revision} onChange={e=>setForm({...form,revision:e.target.value})}/></label></div><label>Milestone plan JSON<textarea required rows="8" value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}/></label><button className="primary" type="submit">Lock exact tranche sum <LockKeyhole size={16}/></button></form>}</div>
}
